# -*- coding: utf-8 -*-
"""customer purchasing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwtsXnBQnk3oiXdiUILtMuGpnBeh1O-G
"""

# STEP 1: Install mlxtend (only needed once in Colab)
!pip install mlxtend

# STEP 2: Import required libraries
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
import matplotlib.pyplot as plt
import seaborn as sns

# STEP 3: Upload the dataset
from google.colab import files
uploaded = files.upload()

# STEP 4: Load the dataset
df = pd.read_csv("sample_transactions.csv")
df.head()

# STEP 5: Transform data to basket format
basket = df.groupby(['TransactionID', 'Item'])['Item'].count().unstack().reset_index().fillna(0).set_index('TransactionID')
basket = basket.applymap(lambda x: 1 if x > 0 else 0)
basket.head()

# STEP 6: Generate frequent itemsets using Apriori
frequent_itemsets = apriori(basket, min_support=0.05, use_colnames=True)
frequent_itemsets.sort_values(by="support", ascending=False).head()

# STEP 7: Generate association rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules = rules.sort_values(by='confidence', ascending=False)
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(10)

# STEP 8: Visualize rules with scatter plot
plt.figure(figsize=(10, 6))
sns.scatterplot(data=rules, x="support", y="confidence", size="lift", hue="lift", alpha=0.7, palette="viridis")
plt.title('Association Rules Support vs Confidence')
plt.xlabel('Support')
plt.ylabel('Confidence')
plt.show()

# STEP 9: Save results to CSV
rules.to_csv("association_rules_output.csv", index=False)
print("Rules exported to association_rules_output.csv")